# Generated by Django 6.0.5 on 2026-06-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_complited',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
