# Generated by Django 6.0.5 on 2026-06-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_completed_at_project_is_complited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_complited',
            new_name='is_completed',
        ),
    ]
