# Generated by Django 6.0.5 on 2026-05-05 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия активности')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия активности')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Дата последней активности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
