# Generated by Django 6.0.5 on 2026-05-05 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('condition_type', models.CharField(choices=[('tasks_created', 'Создано задач'), ('tasks_completed', 'Выполнено задач'), ('high_priority_completed', 'Выполнено важных задач'), ('comments_created', 'Оставлено комментариев'), ('streak_days', 'Дней активности подряд'), ('level_reached', 'Достигнут уровень')], max_length=50, verbose_name='Тип условия')),
                ('condition_value', models.PositiveIntegerField(verbose_name='Значение условия')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='Награда XP')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['condition_type', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='XPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('task_created', 'Создание задачи'), ('task_completed', 'Выполнение задачи'), ('before_deadline', 'Выполнение до дедлайна'), ('high_priority', 'Выполнение важной задачи'), ('comment_created', 'Комментарий'), ('achievement_received', 'Получение достижения')], max_length=50, verbose_name='Действие')),
                ('xp_amount', models.PositiveIntegerField(verbose_name='Количество XP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История XP',
                'verbose_name_plural': 'История XP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='gamification.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ['-received_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
